### ISSUE TITLE
unknown error w/ python prtg script

### ISSUE THREAD

**Issue by feralsboy** [hutchris/prtg#9]
I'm trying to get the python script to work in order to search prtg.
I'm getting the following error.  It seems to indicate that my password
is incorrect.  I used that password to login to the web page.  the password
contains a '#'.

  

File "/Users/admin/scripts/python/broadsoft/prtg-master/prtg.py", line 39, in get_request
    raise(self.AuthenticationError("PRTG authentication failed. Check credentials in config file"))
prtg.AuthenticationError: PRTG authentication failed. Check credentials in config file

/usr/local/bin/python3 --version
Python 3.6.0

**Comment by hutchris** [comment]
Hi

Sorry about the delay. You need to use your passhash for this module instead of your password. If you log into PRTG and look at your account settings you should be able to retrieve your passhash.

Thanks
